version: "3"
services:
  manager:
    build: 
      context: "./manager"
      dockerfile: "Dockerfile.dev"
    image: "manager:latest"
    #stdin_open: true
    #tty: true
    #volumes:
      #- /app/scripts/
      #- "./manager:/app"
    env_file:
      - ".postgres_db_con"
    environment:
      CSV_FILENAME: "data.csv"
      OUTPUT_CSV_FILENAME: "fetched_data.csv"
    depends_on:
      - "db"
  db:
    image: "postgres:latest"
    env_file:
      - ".postgres_db_con"
  adminer:
    image: "adminer"
    ports:
      - "8098:8080"
    depends_on:
      - "db"
  manager_tests:
    depends_on:
      - "db"
      - "manager"
    image: "manager:latest"
    command: "python -m unittest app"